version: "3"

services:
  mongo:
    container_name: wm-challenge-mongo
    image: mongo:3.6.8
    ports: 
      - "${DB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS} 
    logging:
      driver: none
  
  populate_mongo:
    container_name: wm-challenge-mongo-populate
    build:
      context: ./database
    links:
      - mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS} 
    depends_on:
      - mongo

  node:
    container_name: wm-challenge-node
    restart: always
    build: 
      context: ./backend
    ports:
      - "${SERVER_PORT}:4000"
    links:
      - mongo
    volumes:
      - ./backend:/usr/wm-server
      - /usr/wm-server/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_PORT=${SERVER_PORT}
      - MONGODB_SERVER=${MONGODB_SERVER}
      - MONGODB_DB=${MONGODB_DB}      
      - MONGODB_USER=${MONGODB_USER}      
      - MONGODB_PASS=${MONGODB_PASS}
    depends_on:
      - mongo

  front:
    container_name: wm-challenge-app
    restart: always
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/usr/wm-front
      - /usr/wm-front/node_modules
    ports:
      - "${APP_PORT}:4200"
      - "49153:49153"
      - "9876:9876"
      - "49152:49152"